import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { Avatar, Flex, Icon, Text, Button } from '@chakra-ui/react';
import Header from '../components/shared/Header';
import users from '../data/users.json';

const Home: NextPage = () => {
  const logo = users.users[1].avatarUrl;
  console.log(logo, 'logo');

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header logo={logo} />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>TechTorch admin panel</a>
        </h1>

        <div className={styles.grid}>
          <Flex direction='column' pt='50px'>
            <Link href='/users?userId=1' className={styles.card}>
              <Button
                bg='darkblue'
                color='white'
                m='5px'
                pb='10px'
                textAlign='center'
              >
                <Text fontSize='xl' cursor='pointer' pt='20px' pb='8px'>
                  Log in as user 1 (admin) &rarr;
                </Text>
              </Button>
            </Link>

            <Link href='/users/noAccess' className={styles.card}>
              <Button
                bg='darkblue'
                color='white'
                m='5px'
                pb='10px'
                textAlign='center'
              >
                <Text fontSize='xl' pt='20px' cursor='pointer' pb='8px'>
                  Log in as user 2 (viewer) &rarr;
                </Text>
              </Button>
            </Link>
          </Flex>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home
